# Generated by Django 4.2.7 on 2025-05-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_encounter_remove_usersettings_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescribed_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
